twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_nav
        timeout: 0.5
        priority: 10
      teleop:
        topic: cmd_vel_teleop
        timeout: 0.5
        priority: 100
    locks:
      pause:
        topic: pause_navigation
        timeout: 0.0
        priority: 100
        enabled: True